### ISSUE TITLE
Exception thrown on .Net Core 3.0 and SQL Server 2008R2

### ISSUE THREAD

**Issue by JohnJVTK** [dncuug/X.PagedList#187]
In our company I recently migrate a project from .Net Framework 4.8 to .Net Core 3.1.2 but I get the following error on my Index page (where I list elements) when I switch page :
```c#
Incorrect syntax near 'OFFSET'.
Invalid usage of the option NEXT in the FETCH statement.
Incorrect syntax near the keyword 'AS'.
```
I use 8.0.5. version of X.PagedList.Mvc.Core.

Take for example the following code where the "Find" method return an IQueryable<MyObject>.
```c#
const int pageSize = 75;
var pageNumber = page ?? 1;

viewModel.BonsCommande = _bonCommandeService
                .Find(status, searchString, sortOrder, GetUserId())
                .ToPagedList(pageNumber, pageSize);
```

This happens because we run on a SQL Server 2008R2.
I tried on my computer on SQL Server 2016 and I have no problem.
I read that prior to .Net Core 3.0 it was possible to specify .UseRowNumberForPaging() but it is now deprecated and no longer works.
```c#
services.AddDbContext<OrionContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("OrionConnectionString"),
                     sqlServerOptions => sqlServerOptions.UseRowNumberForPaging()));
```
Here is the link from Microsoft where devs explain they won't revert this changes : [https://github.com/dotnet/efcore/issues/16400](url)

Is there any chance you change the way SQL is generated or should I drop SQL Server 2008R2 ?

**Comment by ronaldbarendse** [comment]
Mainstream support for SQL Server 2008 R2 has ended, so I would recommend upgrading: https://docs.microsoft.com/en-gb/archive/blogs/sqlreleaseservices/end-of-mainstream-support-for-sql-server-2008-and-sql-server-2008-r2.

This problem is not related to X.PagedList, as EF Core 3.0 dropped support for row number paging: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#urn.

**Comment by JohnJVTK** [comment]
Yes I knew that but I hoped you had a cheaper solution than upgrading.
I guess I have no choice than migrating to a newer version.
Thank you for your support.

**Comment by ronaldbarendse** [comment]
Well, you upgraded your project to .NET Core, so that already requires you to evaluate whether the server would support that, right? You can always write/generate your own SQL for the paging (if that's even possible with EF Core 3.0) and pass the results to a `StaticPagedList`. FYI I'm just pitching in here, maybe the maintainers of X.PagedList think differently on this...
