### ISSUE TITLE
PagedListRenderOptionsBase

### ISSUE THREAD

**Issue by mmu69** [dncuug/X.PagedList#214]
When upgrading from 8.0.7 to 8.1.0 "PagedListRenderOptionsBase" does not exist anymore.
Since PagedListRenderOptions is a sealed class, there is nothing left we can use to inherit

**Comment by toddlucas** [comment]
We were using a class derived from `PagedListRenderOptions` to support Bootstrap 4, which [changed](https://getbootstrap.com/docs/4.0/migration/#pagination) from previous versions. It appears that the built-in `TwitterBootstrapPager` static is designed for Bootstrap 2.

Given that the library provides customizations as static properties, it seems logical that others might want to provide customizations.

I don't think this is a big deal. We can use other patterns, like a factory method. I understand why it's sealed (the class doesn't need additional properties in a derived class since the library only uses those provided). Just providing feedback since people use different initialization patterns.

**Comment by dunkhi** [comment]
I'm not even seeing the PagedListRenderOptions class with version 8.1.0. Is it still here?
