### ISSUE TITLE
.NET 4.5

### ISSUE THREAD

**Issue by midiway** [dncuug/X.PagedList#52]
The X.PagedList.Mvc Nuget package is targeting .NET >= 4.6

Plz, make it a .NET >= 4.5 package because some hosting providers are still not supporting .NET 4.6

**Comment by masoudhaghi** [comment]
@midiway thanks for raising this issue. I've been having the same issue since replaced the PagedList.Mvc with X.PagedList.Mvc in our latest project which is running on .NET Framework 4.5

The error message suggesting that the Mvc does not exist in the library or the reference is missing from the project.

Error Message:
"The type or namespance name 'Mvc' does not exist in the namespace 'X.PagedList' (are you missing an assembly reference?)"

@kpi-ua is there any way to recompile this library for .NET Framework version 4.5 as well?

Thanks
